### ISSUE TITLE
Issue with output format

### ISSUE THREAD

**Issue by overthink** [aclar48/sortable_challenge#1]
Hi Alex,

I was trying to evaluate your solution but there is a problem with the output format. Please make sure each line in the output file is a Result object as described on http://sortable.com/challenge/, i.e.

```
{
  "product_name": String
  "listings": Array[Listing]
}

```

An example line in the output file should look like:

```json
{"listings": [{"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Red)"}, {"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio Exilim EX-FC150 10.1MP High Speed Digital Camera with 5x Optical Zoom, CMOS Shift Image Stabilization & 2.7-inch LCD (Red)"}, {"currency": "USD", "price": "249.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Black)"}], "product_name": "Casio_Exilim_EX-FC150"}
```

In your case it looks like the values in the `listings` array are objects that have been serialized to strings rather than just the objects themselves.  e.g.

```json
{"product_name":"Panasonic_Lumix_DMC-FS33","listings":["{\"title\":\"Lumix DMC-FS33 + Case + 4GB SDHC (Black, 14MP, Optical Zoom 8x, 3 inch. Touchscreen)\",\"manufacturer\":\"Panasonic\",\"currency\":\"EUR\",\"price\":\"183.99\"}"]}
```

If you are able to fix this up I'd be happy to take another look at your submission.

Thanks!

Mark (from sortable.com)

**Comment by aclar48** [comment]
@overthink The issue has been fixed, sorry about that.

**Comment by overthink** [comment]
No prob. Thanks for the quick fix.
